In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/healthcare_dataset.csv")

In [3]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [4]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [6]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [7]:
df.shape

(55500, 15)

### PASO 1: Exploración de datos

In [8]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

No hay valores nulos en nuestro conjunto de datos de atención médica, ya que el valor de todas las columnas es cero.


#### Problema 1: Inconsistencia en la columna 'Name'
Los registros de la columna 'Name' presentan mayúsculas y minúsculas. Esto puede causar problema al momento de procesar los datos.

In [9]:
display(df[['Name']].head(25))

                   Name
0         Bobby JacksOn
1          LesLie TErRy
2           DaNnY sMitH
3          andrEw waTtS
4         adrIENNE bEll
5         EMILY JOHNSOn
6        edwArD EDWaRDs
7    CHrisTInA MARtinez
8       JASmINe aGuIlaR
9      ChRISTopher BerG
10     mIchElLe daniELs
11       aaRon MARtiNeZ
12        connOR HANsEn
13         rObeRt bAuer
14         bROOkE brady
15   MS. nAtalIE gAMble
16        haley perkins
17  mRS. jamiE cAMPBELl
18         LuKE BuRgEss
19       dANIEL schmIdt
20        tIMOTHY burNs
21   ChRISToPHEr BRiGhT
22      KatHRYn StewArt
23  dR. EilEEn thomPsoN
24       PAUl hEndERsOn

#### Problema 2: Prefijos honoríficos y generacionales en la columna 'Name' y 'Doctor'
Existen registros que contienen títulos honoríficos como (Mr., Mrs., Ms., Dr.) como prefijo y sufijos profesionales como (MD, DDS, DVM, PHD) y generacionales.
Introduce ruido ya que puede generar falsos negativos en detección de duplicados.

#### Prefijos honoríficos

In [10]:
# Para la columna Name
titles_name = df['Name'].str.extract(r'^(\w+\.)\s')
conteo_name = titles_name[0].value_counts()
display(conteo_name)
print(f"\nTotal Name: {conteo_name.sum()}")

0
mR.     119
MR.     114
mr.     101
Dr.      90
dr.      85
Mr.      84
dR.      78
DR.      73
mrs.     44
MRs.     42
MRS.     37
MrS.     36
mRS.     34
Mrs.     31
mrS.     31
mRs.     21
MS.      15
mS.      15
ms.      14
Ms.       7
Name: count, dtype: int64

Total Name: 1071

In [11]:
# Para la columna Doctor
titles_doctor = df['Doctor'].str.extract(r'^(\w+\.)\s')
conteo_doctor = titles_doctor[0].value_counts()
display(conteo_doctor)
print(f"\nTotal Doctor: {conteo_doctor.sum()}")

0
Mr.     386
Dr.     322
Mrs.    293
Ms.      64
Name: count, dtype: int64

Total Doctor: 1065

#### Sufijos profesionales y generacionales

In [12]:
suffix_pattern = r'(?i)\b(Jr\.|Sr\.|II|III|IV|DDS|MD|PhD|DVM)\b'
# Sufijos en Name
conteo_name = df['Name'].str.extractall(suffix_pattern)[0].value_counts()
display(conteo_name)
print(f"\nTotal name :{conteo_name.sum()}")

0
md     139
MD     118
mD     111
Md     109
DDS     54
Dds     42
dDs     42
DdS     41
DDs     37
dDS     35
ddS     30
dds     28
dVM     27
dvM     25
Dvm     23
dVm     21
DvM     21
phD     21
DVM     18
iI      18
pHD     17
PHD     16
DVm     16
Phd     15
PhD     14
dvm     14
pHd     13
II      12
phd     11
Ii       7
ii       6
PHd      6
iII      4
iiI      4
IiI      2
III      2
iii      1
Iv       1
IV       1
Iii      1
iv       1
iIi      1
IIi      1
Name: count, dtype: int64

Total name :1126

In [13]:
# Sufijos en Doctor
conteo_name = df['Doctor'].str.extractall(suffix_pattern)[0].value_counts()
display(conteo_name)
print(f"\nTotal doctor :{conteo_name.sum()}")

0
MD     521
DDS    340
DVM    201
PhD    119
II      32
III     27
IV       6
Name: count, dtype: int64

Total doctor :1246

#### Problema 3: Registros duplicados

Existen 534 registros duplicados.

In [14]:
df.duplicated().sum()

np.int64(534)

In [15]:
duplicados = df[df.duplicated()].sort_values(by="Name")
duplicados

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
54285,ABIgaIL YOung,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
53104,ALIcia taYLoR,78,Male,O+,Asthma,2022-09-18,Dawn Burton,Wright LLC,Aetna,31465.274979,149,Elective,2022-10-15,Aspirin,Inconclusive
50151,AMy GREEN,79,Female,B+,Obesity,2021-03-30,Brett Johnson,Taylor-Williamson,UnitedHealthcare,23402.358491,249,Elective,2021-04-27,Penicillin,Abnormal
51695,ANDREA HansEN,61,Male,O+,Cancer,2021-07-02,Alisha Flores,LLC Clark,Cigna,40026.763948,254,Elective,2021-07-22,Paracetamol,Normal
51916,ANDrEA fREnCH,73,Male,A-,Arthritis,2021-02-08,Danny Oconnor,"Taylor Small, Lin and",UnitedHealthcare,9981.590235,323,Elective,2021-02-24,Ibuprofen,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54679,wiLlIAm mcCOY,80,Male,A-,Asthma,2023-02-20,Whitney Vaughan,"and Walker Glenn, Long",Cigna,3845.397496,158,Emergency,2023-03-10,Penicillin,Normal
51920,wiLliE SChWArtz,49,Female,A-,Arthritis,2019-08-16,Lori Hughes,Schmidt-Ford,Medicare,32612.697020,304,Elective,2019-09-02,Paracetamol,Normal
50070,wiLliam LEe,27,Female,O+,Arthritis,2020-01-31,Lauren Montgomery,Winters-Simon,Cigna,46229.434901,153,Elective,2020-02-13,Lipitor,Normal
53693,willIAM DUnCan,78,Female,B-,Arthritis,2019-08-04,Margaret Rice,"and Hobbs Rice, Miller",UnitedHealthcare,4537.845577,383,Elective,2019-08-17,Aspirin,Abnormal
51964,zaCHAry balL,85,Female,B-,Diabetes,2020-04-25,Matthew Conley,"and Morgan Jones, Matthews",Blue Cross,15207.547262,202,Emergency,2020-05-25,Penicillin,Inconclusive

#### Problema 4: Montos de facturación negativos
Existen valores negativos en la columna 'Billing Amount' que carece de sentido en un contexto hospitalario, ya que un monto de facturación no deberia ser negativo.

In [16]:
valores_negativos = (df['Billing Amount']<0).sum()
print(f"Total de valores negativos:{valores_negativos}")

Total de valores negativos:108

#### Problema 5: Inconsistencias en nombres de hospitales
La columna Hospital presenta inconsistencias de formato, como comas aisladas en el texto, además contiene la conjuncion 'and' al inicio o al final de algunos registros.

In [17]:
registros_coma = df['Hospital'].str.contains(',', na=False).sum()
print(f"Hospitales con coma : {registros_coma}")

Hospitales con coma : 18635

In [18]:
registros_and = df['Hospital'].str.contains(r'(?i)(?:^and\s+|\s+and$)',regex=True , na = False).sum()
print(f"Hospitales con 'and' al inicio o al final: {registros_and}")

Hospitales con 'and' al inicio o al final: 11351

#### Problema 6: Fechas almacenadas como string

Al revisar los registros del DataFrame, se observó que las columnas Date of Admission y Discharge Date fueron insertadas por defecto como tipo de dato texto.

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB